list: $/youpiyoupla/ccy/models/exchanges/columns.yaml
modelClass: Youpiyoupla\Ccy\Models\Exchanges
title: Exchanges
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'youpiyoupla/ccy/exchanges/update/:id'
