list: $/youpiyoupla/ccy/models/coins/columns.yaml
modelClass: Youpiyoupla\Ccy\Models\Coins
title: Coins
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'youpiyoupla/ccy/coins/update/:id'
