list: $/youpiyoupla/ccy/models/ledgers/columns.yaml
modelClass: Youpiyoupla\Ccy\Models\ledgers
title: ledgers
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'youpiyoupla/ccy/ledgers/update/:id'
